### ISSUE TITLE
Wrong generation of spec content

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/dataModel.Environment#14]
# Description
There are some problems in the generation of the spec documents specially related to "**Nitrogen monoxide detected**" it should be "**no**" but the result is "**False**"

# Files affected
- [spec.md](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec.md)
- [spec_DE.md](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec_DE.md)
- [spec_ES.md](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec_DE.md)
- [spec_FR.md](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec_DE.md)

**Comment by albertoabellagarcia** [comment]
You're right it is misinterpreted by the python script as false. To be fixed

**Comment by albertoabellagarcia** [comment]
We got the error, it was a 'feature' of the the yaml reading which allows No, NO yes and Yes and other keywords to get translated into boolean.
this is the fixed function. def read_yaml(fileUrl):
    import yaml
    from yaml.resolver import Resolver
    import re
    import requests
    # required for avoiding that No was replace by false
    for ch in "OoYyNn":
        if ch in Resolver.yaml_implicit_resolvers:
            if len(Resolver.yaml_implicit_resolvers[ch]) == 1:
                del Resolver.yaml_implicit_resolvers[ch]
            else:
                Resolver.yaml_implicit_resolvers[ch] = [x for x in Resolver.yaml_implicit_resolvers[ch] if x[0] != 'tag:yaml.org,2002:bool']


    if fileUrl[0:4] == "http":
        # es URL
        pointer = requests.get(fileUrl)
        return yaml.safe_load(pointer.content.decode('utf-8'))
    else:
        # es file
        file = open(fileUrl, "r")
        return yaml.safe_load(file.read())


We will have to run it for several data models affected by this issue
