### ISSUE TITLE
NoiseLevelObserved missing properties in the specification

### ISSUE THREAD

**Issue by rjvitorino** [smart-data-models/dataModel.Environment#16]
The specification does not cover measurements or attributes regarding Noise Level observations, while in the examples we have these:

```json
  "LAS": 91.6,  
  "LAeq": 67.8,  
  "LAeq_d": 65.4,  
  "LAmax": 94.5,  
```

**Comment by albertoabellagarcia** [comment]
You are right we have an issue with the indenting of the json schema. Fixed. Thanks
