### ISSUE TITLE
Non usable JSON schema in validators

### ISSUE THREAD

**Issue by EliottPaillard** [smart-data-models/dataModel.Environment#23]
Hello,
I wanted to use a JSON schema to test a model with a JSON validator but the schemas look outdated.
I think something goes wrong because of the "$schema" value.
 I believe "http://json-schema.org/schema#" is deprecated now and should be replaced by "https://json-schema.org/draft/2020-12/schema".

The replacement should be made in the main schema but also in each schema in it called by the "$ref" tag.

**Comment by albertoabellagarcia** [comment]
thanks for the input. As mentioned in other issue you opened, both links point to the same file so it is hard to understand how this prevent to use a validator (please provide us with further information) 

Besides this, we do not understand what do you mean in the sentence "The replacement should be made in the main schema but also in each schema in it called by the "$ref" tag." Initially there is only one reference to the meta-schema in the attribute "$schema"

Thanks

**Comment by albertoabellagarcia** [comment]
Running the script to update to the last version https://json-schema.org/draft/2020-12/schema

Initially today all data models will be updated 

Thanks and sorry for the delay

**Comment by EliottPaillard** [comment]
Hey @albertoabellagarcia,

thank you for this update.
It still may be not enough but you should also update the json schemas from https://github.com/smart-data-models/data-models

But maybe you need me to post an issue in the specified repository.
