### ISSUE TITLE
Schema update

### ISSUE THREAD

**Issue by balbert-etraid** [smart-data-models/dataModel.Environment#24]
Hello, I've seen that the schemas have been updated to the latest version. Thing is we were using context.jsonld in our instance of FIWARE, does it affect, or a newer version of the Orion has been deployed supporting this schemas?

We mainly stick with context.jsonld such as this one:

```json
{
    "@context": [
        {
            "refPilot": {
                "@id": "https://raw.githubusercontent.com/balbert-etraid/twinair/main/models/pilot/context.jsonld",
                "@type": "ngsi-ld:Relationship"
            },
            "refRoom": {
                "@id": "https://raw.githubusercontent.com/balbert-etraid/twinair/main/models/room/context.jsonld",
                "@type": "ngsi-ld:Relationship"
            }
        },
        "https://raw.githubusercontent.com/smart-data-models/dataModel.Device/master/context.jsonld",
        "https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld"
    ]
}
```

Best,

Borja A.

**Comment by albertoabellagarcia** [comment]
The updated was to the last meta schema version because there were some issues with validators. Initially the update is not affecting the context. What it is true is that we have a pending issue with an updated of the core context https://github.com/smart-data-models/dataModel.Transportation/issues/23

**Comment by albertoabellagarcia** [comment]
what we are doing today is to fix a bug regarding the core context. Again it should not affect you at all.
